login: &login
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: postgres
  password: yucatec0
  host: 127.0.0.1

development:
  <<: *login
  database: linkedin

test: &test
  <<: *login
  database: linkedin_test

production:
  <<: *login
  database: linkedin

staging:
  <<: *login
  database: linkedin_staging
